(function () {
  "use strict";

  var EXAMPLES = [
    "A habit tracker with streaks and widgets",
    "A local cafe finder with maps and favorites",
    "A personal finance app with budgets",
    "A meditation timer with Live Activities"
  ];

  var FILES = {
    "ContentView.swift": [
      [{ t: "cm", v: "// Generated by Nativ AI · SwiftUI" }],
      [{ t: "kw", v: "import" }, { t: "ty", v: " SwiftUI" }],
      [],
      [{ t: "kw", v: "struct" }, { t: "ty", v: " ContentView" }, { t: "op", v: ": " }, { t: "ty", v: "View" }, { t: "op", v: " {" }],
      [{ t: "kw", v: "    @State" }, { t: "kw", v: " private" }, { t: "kw", v: " var" }, { t: "op", v: " items: [" }, { t: "ty", v: "AppItem" }, { t: "op", v: "] = SampleData.items" }],
      [],
      [{ t: "kw", v: "    var" }, { t: "fn", v: " body" }, { t: "op", v: ": " }, { t: "kw", v: "some" }, { t: "ty", v: " View" }, { t: "op", v: " {" }],
      [{ t: "ty", v: "        NavigationStack" }, { t: "op", v: " {" }],
      [{ t: "ty", v: "            List" }, { t: "op", v: "(items) { item " }, { t: "kw", v: "in" }],
      [{ t: "ty", v: "                ItemRow" }, { t: "op", v: "(item: item)" }],
      [{ t: "op", v: "            }" }],
      [{ t: "op", v: "            .navigationTitle(" }, { t: "str", v: "appName" }, { t: "op", v: ")" }],
      [{ t: "op", v: "            .toolbar {" }],
      [{ t: "ty", v: "                Button" }, { t: "op", v: "(" }, { t: "str", v: "\"Add\"" }, { t: "op", v: ", systemImage: " }, { t: "str", v: "\"plus\"" }, { t: "op", v: ") { }" }],
      [{ t: "op", v: "            }" }],
      [{ t: "op", v: "        }" }],
      [{ t: "op", v: "    }" }],
      [{ t: "op", v: "}" }]
    ],
    "AppItem.swift": [
      [{ t: "kw", v: "import" }, { t: "ty", v: " Foundation" }],
      [],
      [{ t: "kw", v: "struct" }, { t: "ty", v: " AppItem" }, { t: "op", v: ": " }, { t: "ty", v: "Identifiable" }, { t: "op", v: ", " }, { t: "ty", v: "Hashable" }, { t: "op", v: " {" }],
      [{ t: "kw", v: "    let" }, { t: "op", v: " id = " }, { t: "ty", v: "UUID" }, { t: "op", v: "()" }],
      [{ t: "kw", v: "    var" }, { t: "op", v: " title: " }, { t: "ty", v: "String" }],
      [{ t: "kw", v: "    var" }, { t: "op", v: " detail: " }, { t: "ty", v: "String" }],
      [{ t: "op", v: "}" }]
    ],
    "NativApp.swift": [
      [{ t: "kw", v: "import" }, { t: "ty", v: " SwiftUI" }],
      [],
      [{ t: "op", v: "@main" }],
      [{ t: "kw", v: "struct" }, { t: "ty", v: " NativApp" }, { t: "op", v: ": " }, { t: "ty", v: "App" }, { t: "op", v: " {" }],
      [{ t: "kw", v: "    var" }, { t: "fn", v: " body" }, { t: "op", v: ": " }, { t: "kw", v: "some" }, { t: "ty", v: " Scene" }, { t: "op", v: " {" }],
      [{ t: "ty", v: "        WindowGroup" }, { t: "op", v: " { " }, { t: "ty", v: "ContentView" }, { t: "op", v: "() }" }],
      [{ t: "op", v: "    }" }],
      [{ t: "op", v: "}" }]
    ],
    "Info.plist": [
      [{ t: "cm", v: "<!-- App Store Connect ready -->" }],
      [{ t: "op", v: "<key>CFBundleDisplayName</key>" }],
      [{ t: "op", v: "<string>" }, { t: "ty", v: "appName" }, { t: "op", v: "</string>" }],
      [{ t: "op", v: "<key>CFBundleShortVersionString</key>" }],
      [{ t: "op", v: "<string>1.0.0</string>" }],
      [{ t: "op", v: "<key>UILaunchScreen</key>" }],
      [{ t: "op", v: "<dict/>" }]
    ]
  };

  var state = {
    view: "landing",
    prompt: "",
    appName: "MyApp",
    activeFile: "ContentView.swift",
    building: false,
    built: false,
    logs: [],
    submitOpen: false,
    submitStep: 0,
    submitting: false,
    teamId: "",
    bundleId: "",
    toast: null
  };

  function esc(s) {
    return String(s == null ? "" : s)
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;")
      .replace(/'/g, "&#39;");
  }

  function deriveName(prompt) {
    var p = (prompt || "").trim();
    if (!p) return "MyApp";
    var words = p.replace(/[^a-zA-Z0-9\s]/g, " ").split(/\s+/).filter(Boolean);
    var pick = words.slice(0, 2).map(function (w) {
      return w.charAt(0).toUpperCase() + w.slice(1).toLowerCase();
    });
    return (pick.join("") || "MyApp").slice(0, 24);
  }

  function renderCode(file, appName) {
    var lines = FILES[file] || [];
    return lines.map(function (line, i) {
      var html = line.map(function (tok) {
        var v = tok.v === "appName"
          ? (tok.t === "str" ? '"' + appName + '"' : appName)
          : tok.v;
        return '<span class="' + tok.t + '">' + esc(v) + "</span>";
      }).join("");
      if (!html) html = "&nbsp;";
      return '<div class="line"><span class="ln">' + (i + 1) + '</span><span>' + html + "</span></div>";
    }).join("");
  }

  function previewItems(prompt) {
    var lower = (prompt || "").toLowerCase();
    if (lower.indexOf("habit") !== -1) {
      return [
        ["Morning run", "7-day streak"],
        ["Read 20 pages", "On track"],
        ["Drink water", "5 / 8 cups"]
      ];
    }
    if (lower.indexOf("cafe") !== -1 || lower.indexOf("map") !== -1) {
      return [
        ["Harbor Roast", "0.4 mi · Open"],
        ["Bean Theory", "0.9 mi · Busy"],
        ["Northside Pour", "1.2 mi · Quiet"]
      ];
    }
    if (lower.indexOf("finance") !== -1 || lower.indexOf("budget") !== -1) {
      return [
        ["Groceries", "$186 remaining"],
        ["Transit", "$42 remaining"],
        ["Fun", "$95 remaining"]
      ];
    }
    if (lower.indexOf("meditat") !== -1) {
      return [
        ["Breath focus", "10 min"],
        ["Body scan", "15 min"],
        ["Evening wind-down", "8 min"]
      ];
    }
    return [
      ["Getting started", "Built with Nativ"],
      ["Your first screen", "Native SwiftUI"],
      ["Ready to ship", "App Store Connect"]
    ];
  }

  function pushLog(cls, msg) {
    state.logs.push({ cls: cls, msg: msg, t: new Date() });
    if (state.logs.length > 80) state.logs.shift();
  }

  function brandMark() {
    return '<span class="brand-mark" aria-hidden="true"></span>';
  }

  function renderLanding() {
    var chips = EXAMPLES.map(function (ex) {
      return '<button type="button" class="chip" data-example="' + esc(ex) + '">' + esc(ex) + "</button>";
    }).join("");

    return (
      '<header class="site-header"><div class="wrap nav">' +
        '<a class="brand" href="#top">' + brandMark() + "Nativ</a>" +
        '<div class="nav-links">' +
          '<a class="nav-link" href="#features">Features</a>' +
          '<a class="nav-link" href="#publish">Publish</a>' +
          '<button type="button" class="btn" id="nav-start">Open compiler</button>' +
        "</div>" +
      "</div></header>" +
      '<section class="hero" id="top"><div class="wrap hero-grid">' +
        "<div>" +
          '<div class="brand-hero">Nativ</div>' +
          "<h1>Build iOS apps with AI</h1>" +
          '<p class="lede">Describe your idea. Get a native Swift project, compile it in the cloud Xcode toolchain, and submit to App Store Connect.</p>' +
          '<div class="prompt-box">' +
            '<textarea id="prompt" placeholder="Describe the iPhone app you want to build…">' + esc(state.prompt) + "</textarea>" +
            '<div class="prompt-actions">' +
              '<div class="chips">' + chips + "</div>" +
              '<button type="button" class="btn" id="build-btn">Generate &amp; compile</button>' +
            "</div>" +
          "</div>" +
        "</div>" +
        '<div class="phone-stage" aria-hidden="true">' +
          '<div class="phone-notch"></div>' +
          '<div class="phone-screen">' +
            '<div class="phone-status"><span>9:41</span><span>5G</span></div>' +
            '<div class="preview-card">' +
              '<div class="preview-title">Live preview</div>' +
              '<div class="preview-row"></div>' +
              '<div class="preview-row short"></div>' +
              '<div class="preview-row"></div>' +
              '<div class="preview-cta"></div>' +
            "</div>" +
          "</div>" +
        "</div>" +
      "</div></section>" +
      '<section class="section" id="features"><div class="wrap">' +
        "<h2>Native Swift. Real Xcode.</h2>" +
        '<p class="lede">Not a web wrapper. Nativ generates SwiftUI, runs the Apple toolchain in the cloud, and keeps your project exportable.</p>' +
        '<div class="feature-list">' +
          "<article class=\"feature\"><h3>Cloud Xcode compiler</h3><p>Build, archive, and validate with a browser-based Xcode workflow — no Mac required to start.</p></article>" +
          "<article class=\"feature\"><h3>SwiftUI you own</h3><p>Read every file, tweak the project, export the full Xcode package whenever you want.</p></article>" +
          "<article class=\"feature\"><h3>App Store Connect</h3><p>Connect your Apple Developer team and submit builds, metadata, and privacy details in two clicks.</p></article>" +
        "</div>" +
      "</div></section>" +
      '<section class="section" id="publish"><div class="wrap">' +
        "<h2>From finished app to App Store review.</h2>" +
        '<p class="lede">Signing, packaging, and delivery are automated once your developer account is linked.</p>' +
        '<button type="button" class="btn btn-amber" id="cta-publish">Submit to App Store Connect</button>' +
      "</div></section>" +
      '<footer class="wrap site-footer"><span>Nativ · Native iOS with AI</span><span>Demo compiler · Not affiliated with Apple</span></footer>'
    );
  }

  function renderStudio() {
    var files = Object.keys(FILES).map(function (f) {
      var active = f === state.activeFile ? " active" : "";
      return '<div class="file' + active + '" data-file="' + esc(f) + '"><span class="ico">swift</span>' + esc(f) + "</div>";
    }).join("");

    var items = previewItems(state.prompt).map(function (row) {
      return '<div class="sim-item"><strong>' + esc(row[0]) + "</strong>" + esc(row[1]) + "</div>";
    }).join("");

    var logs = state.logs.map(function (l) {
      return '<div class="' + l.cls + '">' + esc(l.msg) + "</div>";
    }).join("") || '<div class="dim">Ready. Press Compile to run xcodebuild.</div>';

    var buildLabel = state.building ? "Compiling…" : state.built ? "Recompile" : "Compile";

    return (
      '<div class="studio">' +
        '<div class="studio-bar">' +
          '<div class="studio-title">' +
            '<div class="traffic" aria-hidden="true"><span class="r"></span><span class="y"></span><span class="g"></span></div>' +
            "<strong>" + esc(state.appName) + ".xcodeproj</strong>" +
            (state.built ? '<span class="badge">Build succeeded</span>' : "") +
          "</div>" +
          '<div class="studio-actions">' +
            '<button type="button" class="btn btn-ghost" id="back-home">← Home</button>' +
            '<button type="button" class="btn btn-ghost" id="compile-btn"' + (state.building ? " disabled" : "") + ">" + buildLabel + "</button>" +
            '<button type="button" class="btn btn-amber" id="submit-btn">Submit to App Store Connect</button>' +
          "</div>" +
        "</div>" +
        '<div class="studio-body">' +
          '<aside class="pane">' +
            '<div class="pane-head">Project navigator</div>' +
            '<div class="file-tree">' +
              '<div class="folder">' + esc(state.appName) + "</div>" +
              files +
            "</div>" +
          "</aside>" +
          '<section class="pane" style="position:relative">' +
            '<div class="pane-head"><span>' + esc(state.activeFile) + '</span><span>Swift</span></div>' +
            '<div class="editor">' + renderCode(state.activeFile, state.appName) + "</div>" +
            (state.building ? '<div class="building-overlay"><div class="spinner" aria-label="Building"></div></div>' : "") +
          "</section>" +
          '<section class="pane preview-pane">' +
            '<div>' +
              '<div class="pane-head"><span>Simulator</span><span>iPhone 16</span></div>' +
              '<div class="device-frame"><div class="device"><div class="device-inner">' +
                "<h4>" + esc(state.appName) + "</h4>" +
                "<p>" + esc((state.prompt || "Your generated SwiftUI app").slice(0, 110)) + "</p>" +
                '<div class="sim-list">' + items + "</div>" +
              "</div></div></div>" +
            "</div>" +
            '<div class="console" id="console">' +
              '<div class="dim">Nativ Cloud Xcode · xcodebuild</div>' +
              logs +
            "</div>" +
          "</section>" +
        "</div>" +
      "</div>"
    );
  }

  function renderSubmitModal() {
    if (!state.submitOpen) return "";
    var steps = [
      "Validate archive with cloud Xcode",
      "Upload build to App Store Connect",
      "Attach metadata & privacy nutrition labels",
      "Submit for App Review"
    ].map(function (label, i) {
      var cls = "step";
      if (i < state.submitStep) cls += " done";
      if (i === state.submitStep) cls += " active";
      var mark = i < state.submitStep ? "✓" : String(i + 1);
      return '<div class="' + cls + '"><span class="dot">' + mark + "</span><span>" + esc(label) + "</span></div>";
    }).join("");

    var done = state.submitStep >= 4;
    return (
      '<div class="modal" id="submit-modal">' +
        '<div class="sheet" role="dialog" aria-labelledby="submit-title">' +
          '<h2 id="submit-title">Submit to App Store Connect</h2>' +
          "<p>Connect your Apple Developer team. Nativ prepares signing, the archive, and the ASC upload.</p>" +
          '<div class="field"><label for="team-id">Team ID</label>' +
            '<input id="team-id" placeholder="ABCDE12345" value="' + esc(state.teamId) + '"' + (done || state.submitting ? " disabled" : "") + " /></div>" +
          '<div class="field"><label for="bundle-id">Bundle ID</label>' +
            '<input id="bundle-id" placeholder="com.you.' + esc(state.appName.toLowerCase()) + '" value="' + esc(state.bundleId) + '"' + (done || state.submitting ? " disabled" : "") + " /></div>" +
          '<div class="steps">' + steps + "</div>" +
          '<div class="sheet-actions">' +
            '<button type="button" class="btn btn-ghost" id="close-submit">Close</button>' +
            (done
              ? '<button type="button" class="btn" id="done-submit">Done</button>'
              : '<button type="button" class="btn btn-amber" id="confirm-submit"' + (state.submitting ? " disabled" : "") + ">" +
                  (state.submitting ? "Submitting…" : "Submit build") +
                "</button>") +
          "</div>" +
        "</div>" +
      "</div>"
    );
  }

  function renderToast() {
    if (!state.toast) return "";
    return '<div class="toast" role="status">' + esc(state.toast) + "</div>";
  }

  function render() {
    var root = document.getElementById("app");
    var html = state.view === "studio" ? renderStudio() : renderLanding();
    html += renderSubmitModal();
    html += renderToast();
    root.innerHTML = html;
    bind();
    var consoleEl = document.getElementById("console");
    if (consoleEl) consoleEl.scrollTop = consoleEl.scrollHeight;
  }

  function openStudio(fromPrompt) {
    if (fromPrompt != null) state.prompt = fromPrompt;
    state.appName = deriveName(state.prompt);
    state.view = "studio";
    state.built = false;
    state.logs = [];
    state.bundleId = state.bundleId || ("com.nativ." + state.appName.toLowerCase().replace(/[^a-z0-9]/g, ""));
    pushLog("info", "→ Project generated: " + state.appName + ".xcodeproj");
    pushLog("dim", "SwiftUI sources ready · waiting for compile");
    render();
    runCompile();
  }

  function runCompile() {
    if (state.building) return;
    state.building = true;
    state.built = false;
    pushLog("info", "$ xcodebuild -scheme " + state.appName + " -destination 'platform=iOS Simulator,name=iPhone 16'");
    pushLog("dim", "Compiling Swift module " + state.appName + "…");
    render();

    var phases = [
      { delay: 500, cls: "dim", msg: "Compile ContentView.swift" },
      { delay: 900, cls: "dim", msg: "Compile AppItem.swift" },
      { delay: 1300, cls: "dim", msg: "Link " + state.appName + " (arm64)" },
      { delay: 1700, cls: "ok", msg: "** BUILD SUCCEEDED **" },
      { delay: 2000, cls: "info", msg: "Installed on iPhone 16 Simulator" }
    ];

    phases.forEach(function (p) {
      setTimeout(function () {
        pushLog(p.cls, p.msg);
        if (p.msg.indexOf("BUILD SUCCEEDED") !== -1) {
          state.building = false;
          state.built = true;
        }
        render();
      }, p.delay);
    });
  }

  function runSubmit() {
    if (state.submitting) return;
    var team = (document.getElementById("team-id") || {}).value || state.teamId;
    var bundle = (document.getElementById("bundle-id") || {}).value || state.bundleId;
    state.teamId = (team || "").trim();
    state.bundleId = (bundle || "").trim();
    if (!state.teamId || !state.bundleId) {
      state.toast = "Enter your Team ID and Bundle ID to continue.";
      render();
      setTimeout(function () { state.toast = null; render(); }, 2200);
      return;
    }
    if (!state.built && state.view === "studio") {
      state.toast = "Compile the project before submitting.";
      render();
      setTimeout(function () { state.toast = null; render(); }, 2200);
      return;
    }

    state.submitting = true;
    state.submitStep = 0;
    render();

    var ticks = [0, 1, 2, 3, 4];
    ticks.forEach(function (step, idx) {
      setTimeout(function () {
        state.submitStep = step;
        if (step === 4) {
          state.submitting = false;
          state.toast = "Build uploaded · waiting for App Review";
          pushLog("ok", "Uploaded " + state.bundleId + " to App Store Connect (Team " + state.teamId + ")");
          setTimeout(function () { state.toast = null; render(); }, 2800);
        }
        render();
      }, 700 * (idx + 1));
    });
  }

  function bind() {
    var prompt = document.getElementById("prompt");
    if (prompt) {
      prompt.oninput = function (e) { state.prompt = e.target.value; };
    }

    document.querySelectorAll("[data-example]").forEach(function (el) {
      el.onclick = function () {
        state.prompt = el.getAttribute("data-example") || "";
        render();
        var ta = document.getElementById("prompt");
        if (ta) ta.focus();
      };
    });

    var buildBtn = document.getElementById("build-btn");
    if (buildBtn) {
      buildBtn.onclick = function () {
        var text = (document.getElementById("prompt") || {}).value || state.prompt;
        if (!(text || "").trim()) {
          state.toast = "Describe your app idea first.";
          render();
          setTimeout(function () { state.toast = null; render(); }, 2000);
          return;
        }
        openStudio(text.trim());
      };
    }

    var navStart = document.getElementById("nav-start");
    if (navStart) {
      navStart.onclick = function () {
        if (!state.prompt.trim()) state.prompt = EXAMPLES[0];
        openStudio(state.prompt);
      };
    }

    var ctaPublish = document.getElementById("cta-publish");
    if (ctaPublish) {
      ctaPublish.onclick = function () {
        if (state.view !== "studio") {
          if (!state.prompt.trim()) state.prompt = EXAMPLES[0];
          openStudio(state.prompt);
          setTimeout(function () {
            state.submitOpen = true;
            state.submitStep = 0;
            render();
          }, 2100);
          return;
        }
        state.submitOpen = true;
        state.submitStep = 0;
        render();
      };
    }

    var back = document.getElementById("back-home");
    if (back) back.onclick = function () { state.view = "landing"; render(); };

    var compile = document.getElementById("compile-btn");
    if (compile) compile.onclick = function () { runCompile(); };

    var submit = document.getElementById("submit-btn");
    if (submit) {
      submit.onclick = function () {
        state.submitOpen = true;
        state.submitStep = 0;
        state.submitting = false;
        render();
      };
    }

    document.querySelectorAll("[data-file]").forEach(function (el) {
      el.onclick = function () {
        state.activeFile = el.getAttribute("data-file");
        render();
      };
    });

    var modal = document.getElementById("submit-modal");
    if (modal) {
      modal.onclick = function (e) {
        if (e.target.id === "submit-modal") {
          state.submitOpen = false;
          render();
        }
      };
    }
    var close = document.getElementById("close-submit");
    if (close) close.onclick = function () { state.submitOpen = false; render(); };
    var done = document.getElementById("done-submit");
    if (done) done.onclick = function () { state.submitOpen = false; render(); };
    var confirm = document.getElementById("confirm-submit");
    if (confirm) confirm.onclick = function () { runSubmit(); };

    var team = document.getElementById("team-id");
    if (team) team.oninput = function (e) { state.teamId = e.target.value; };
    var bundle = document.getElementById("bundle-id");
    if (bundle) bundle.oninput = function (e) { state.bundleId = e.target.value; };
  }

  render();
})();
