-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQglHcwM6vJV9bi1SIB
MkwmcsHa9+psprsrlkMtWuit0FSgCgYIKoZIzj0DAQehRANCAATqzWK6WubNgWJh
eTve+vIOjehXcvgqM41u+TAiTyb6W9l/5oJFjEe0tPe1q6PcvUQTZfeIAT9YVtuV
9SK3a84e
-----END PRIVATE KEY-----